from __future__ import annotations

from app.services.blueprints.types import BlueprintDefinition

PROVISIONING_BLUEPRINTS: list[BlueprintDefinition] = [
    {
        "id": "aws-ec2-private-service",
        "kind": "provisioning",
        "version": "2026-03-18",
        "name": "AWS EC2 Private Service",
        "summary": "Provision a VPC, private EC2 host, security groups, and IAM for an internal workload.",
        "resources_or_actions": ["VPC", "Private subnet", "EC2", "Security groups", "IAM role"],
        "required_inputs": [
            {
                "key": "region",
                "label": "AWS Region",
                "description": "Deployment region for the workload",
                "required": True,
                "risk_class": "safe",
                "default_value": "ap-southeast-1",
            },
            {
                "key": "instance_type",
                "label": "Instance Type",
                "description": "EC2 sizing for the service host",
                "required": True,
                "risk_class": "cost",
                "default_value": "t3.medium",
            },
            {
                "key": "ssh_cidr",
                "label": "SSH Allow List",
                "description": "CIDR allowed to reach SSH",
                "required": True,
                "risk_class": "network",
                "default_value": "10.0.0.0/16",
            },
        ],
        "steps": [
            {
                "id": "network",
                "type": "resource",
                "title": "Create private network",
                "description": "Create VPC, subnets, route tables, and a bastion-free private topology.",
                "required_inputs": ["region"],
                "expected_result": "Private networking exists for the workload without direct public exposure.",
            },
            {
                "id": "compute",
                "type": "resource",
                "title": "Launch service host",
                "description": "Create IAM role, security groups, and an EC2 instance for the application.",
                "required_inputs": ["instance_type", "ssh_cidr"],
                "expected_result": "Application host is reachable only through the approved management path.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate baseline reachability",
                "description": "Confirm the instance boots, IAM is attached, and the host reports ready.",
                "required_inputs": [],
                "expected_result": "Provisioned resources are healthy and ready for configuration steps.",
            },
        ],
    },
    {
        "id": "aws-ecs-public-api",
        "kind": "provisioning",
        "version": "2026-03-18",
        "name": "AWS ECS Public API",
        "summary": "Provision a VPC, load balancer, ECS service, and supporting IAM for an internet-facing API.",
        "resources_or_actions": ["VPC", "ALB", "ECS service", "ECR", "CloudWatch logs"],
        "required_inputs": [
            {
                "key": "region",
                "label": "AWS Region",
                "description": "Deployment region for the service",
                "required": True,
                "risk_class": "safe",
                "default_value": "us-east-1",
            },
            {
                "key": "service_port",
                "label": "Service Port",
                "description": "Listener port exposed by the API",
                "required": True,
                "risk_class": "network",
                "default_value": "8080",
            },
            {
                "key": "desired_count",
                "label": "Desired Task Count",
                "description": "Number of ECS tasks to keep running",
                "required": True,
                "risk_class": "cost",
                "default_value": "2",
            },
        ],
        "steps": [
            {
                "id": "network",
                "type": "resource",
                "title": "Provision public service network",
                "description": "Create VPC, public/private subnets, routing, and security boundaries.",
                "required_inputs": ["region", "service_port"],
                "expected_result": "The service network supports public ingress through the load balancer only.",
            },
            {
                "id": "runtime",
                "type": "resource",
                "title": "Deploy ECS runtime",
                "description": "Create cluster, task definition, service, and log group for the API.",
                "required_inputs": ["desired_count"],
                "expected_result": "An ECS service is ready to receive application container images.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate endpoint readiness",
                "description": "Confirm the ALB target group and ECS tasks are healthy.",
                "required_inputs": [],
                "expected_result": "The public API endpoint is healthy and routable through the ALB.",
            },
        ],
    },
    {
        "id": "aws-rds-app-stack",
        "kind": "provisioning",
        "version": "2026-03-18",
        "name": "AWS App Stack with RDS",
        "summary": "Provision compute, database, private networking, and secrets boundaries for a stateful app.",
        "resources_or_actions": ["VPC", "EC2 or ECS", "RDS PostgreSQL", "Secrets Manager", "Security groups"],
        "required_inputs": [
            {
                "key": "region",
                "label": "AWS Region",
                "description": "Deployment region for the stack",
                "required": True,
                "risk_class": "safe",
                "default_value": "us-west-2",
            },
            {
                "key": "database_instance_class",
                "label": "Database Instance Class",
                "description": "RDS sizing for the workload",
                "required": True,
                "risk_class": "cost",
                "default_value": "db.t4g.micro",
            },
            {
                "key": "public_ingress_cidr",
                "label": "Public Ingress CIDR",
                "description": "Allowed ingress range for the application entry point",
                "required": True,
                "risk_class": "network",
                "default_value": "0.0.0.0/0",
            },
        ],
        "steps": [
            {
                "id": "network",
                "type": "resource",
                "title": "Provision isolated network zones",
                "description": "Create application and database subnets with dedicated security groups.",
                "required_inputs": ["region", "public_ingress_cidr"],
                "expected_result": "Application and database resources are isolated with controlled connectivity.",
            },
            {
                "id": "stateful",
                "type": "resource",
                "title": "Create app and database services",
                "description": "Provision application compute, RDS PostgreSQL, and secrets storage.",
                "required_inputs": ["database_instance_class"],
                "expected_result": "The stateful app stack is provisioned with database credentials under managed storage.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate app to database path",
                "description": "Confirm the application security group can reach the database and health checks pass.",
                "required_inputs": [],
                "expected_result": "The application and database topology is ready for configuration and deployment.",
            },
        ],
    },
]

CONFIGURATION_BLUEPRINTS: list[BlueprintDefinition] = [
    {
        "id": "openclaw-install-configure",
        "kind": "configuration",
        "version": "2026-03-18",
        "name": "OpenClaw Installation and Configuration",
        "summary": "Install OpenClaw, configure service settings, and validate the runtime automatically on AWS hosts.",
        "resources_or_actions": ["Install packages", "Configure service files", "OpenClaw service validation"],
        "required_inputs": [
            {
                "key": "openclaw_version",
                "label": "OpenClaw Version",
                "description": "Version of OpenClaw to install",
                "required": True,
                "risk_class": "safe",
                "default_value": "latest",
            },
            {
                "key": "admin_cidr",
                "label": "Admin Access CIDR",
                "description": "CIDR allowed to reach the OpenClaw admin endpoint",
                "required": True,
                "risk_class": "network",
                "default_value": "10.0.0.0/16",
            },
            {
                "key": "license_key",
                "label": "OpenClaw License Key",
                "description": "License or entitlement required for activation",
                "required": True,
                "risk_class": "data",
            },
        ],
        "steps": [
            {
                "id": "packages",
                "type": "action",
                "title": "Install OpenClaw packages",
                "description": "Install OpenClaw dependencies and the requested package version on the target host.",
                "required_inputs": ["openclaw_version"],
                "expected_result": "OpenClaw binaries and dependencies are present on the host.",
            },
            {
                "id": "configure",
                "type": "action",
                "title": "Configure OpenClaw service",
                "description": "Write service configuration, secrets, and network policy for the admin endpoint.",
                "required_inputs": ["admin_cidr", "license_key"],
                "expected_result": "OpenClaw is configured with approved network access and activation data.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate OpenClaw runtime",
                "description": "Start the service and confirm health checks and key workflows succeed.",
                "required_inputs": [],
                "expected_result": "OpenClaw is running and reports healthy after configuration.",
            },
        ],
        "post_deploy_checks": {
            "services": ["openclaw"],
            "package_versions": ["openclaw"],
            "health_checks": [
                {
                    "name": "OpenClaw service active",
                    "type": "command",
                    "command": "systemctl is-active openclaw",
                    "success_contains": "active",
                },
                {
                    "name": "OpenClaw health endpoint",
                    "type": "http",
                    "url": "http://localhost:8080/health",
                    "expected_status": 200,
                },
            ],
            "service_logs": [{"name": "OpenClaw", "service": "openclaw"}],
        },
    },
    {
        "id": "docker-compose-app-bootstrap",
        "kind": "configuration",
        "version": "2026-03-18",
        "name": "Docker Compose App Bootstrap",
        "summary": "Install Docker, lay down Compose assets, and validate an application stack on a host.",
        "resources_or_actions": ["Install Docker", "Render Compose files", "Start services", "Validate health"],
        "required_inputs": [
            {
                "key": "compose_project_name",
                "label": "Compose Project Name",
                "description": "Project identifier used by Docker Compose",
                "required": True,
                "risk_class": "safe",
                "default_value": "app-stack",
            },
            {
                "key": "published_port",
                "label": "Published Port",
                "description": "Port exposed by the service stack",
                "required": True,
                "risk_class": "network",
                "default_value": "8080",
            },
        ],
        "steps": [
            {
                "id": "runtime",
                "type": "action",
                "title": "Install container runtime",
                "description": "Install Docker Engine, Compose plugin, and runtime prerequisites.",
                "required_inputs": [],
                "expected_result": "The host can start and manage containerized workloads.",
            },
            {
                "id": "compose",
                "type": "action",
                "title": "Render and start Compose stack",
                "description": "Render Compose files, secrets, and environment overrides for the app stack.",
                "required_inputs": ["compose_project_name", "published_port"],
                "expected_result": "The Compose stack is started with the requested project name and port.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate container services",
                "description": "Confirm containers stay healthy and the published port answers expected probes.",
                "required_inputs": [],
                "expected_result": "The Compose application is healthy and reachable on the expected port.",
            },
        ],
        "post_deploy_checks": {
            "services": ["docker"],
            "package_versions": ["docker", "docker-compose-plugin"],
            "health_checks": [
                {
                    "name": "Docker daemon active",
                    "type": "command",
                    "command": "systemctl is-active docker",
                    "success_contains": "active",
                },
                {
                    "name": "Compose stack processes",
                    "type": "command",
                    "command": "docker compose ps --format json",
                    "success_contains": "\"State\":\"running\"",
                },
            ],
            "service_logs": [{"name": "Docker", "service": "docker"}],
        },
    },
    {
        "id": "host-observability-baseline",
        "kind": "configuration",
        "version": "2026-03-18",
        "name": "Host Observability Baseline",
        "summary": "Install logging, metrics, and system inventory collectors for a newly provisioned host.",
        "resources_or_actions": ["Install CloudWatch agent", "Collect system logs", "Validate telemetry"],
        "required_inputs": [
            {
                "key": "log_retention_days",
                "label": "Log Retention Days",
                "description": "Retention period for forwarded logs",
                "required": True,
                "risk_class": "cost",
                "default_value": "14",
            },
            {
                "key": "inventory_schedule",
                "label": "Inventory Collection Schedule",
                "description": "Cron-style schedule for system inventory capture",
                "required": True,
                "risk_class": "safe",
                "default_value": "0 */6 * * *",
            },
        ],
        "steps": [
            {
                "id": "collector",
                "type": "action",
                "title": "Install telemetry collectors",
                "description": "Install agents and scripts for logs, metrics, and system inventory.",
                "required_inputs": [],
                "expected_result": "Telemetry tooling is present on the host.",
            },
            {
                "id": "configure",
                "type": "action",
                "title": "Configure log and inventory forwarding",
                "description": "Apply retention, schedule, and destination settings for observability data.",
                "required_inputs": ["log_retention_days", "inventory_schedule"],
                "expected_result": "Logs and system inventory are forwarded with the requested policy.",
            },
            {
                "id": "validate",
                "type": "validation",
                "title": "Validate telemetry delivery",
                "description": "Confirm log streams, metrics, and inventory data are visible after deployment.",
                "required_inputs": [],
                "expected_result": "Post-deploy logging and system visibility are active for the host.",
            },
        ],
        "post_deploy_checks": {
            "services": ["amazon-cloudwatch-agent"],
            "package_versions": ["amazon-cloudwatch-agent"],
            "health_checks": [
                {
                    "name": "CloudWatch agent active",
                    "type": "command",
                    "command": "systemctl is-active amazon-cloudwatch-agent",
                    "success_contains": "active",
                }
            ],
            "service_logs": [{"name": "CloudWatch Agent", "service": "amazon-cloudwatch-agent"}],
        },
    },
]

BLUEPRINT_CATALOG: list[BlueprintDefinition] = PROVISIONING_BLUEPRINTS + CONFIGURATION_BLUEPRINTS
